### ISSUE TITLE
Fix Gamification Modal z-index

### ISSUE THREAD

**Issue by yassingamalz** [yassingamalz/Rateel#19]
![Image](https://github.com/user-attachments/assets/40cf6a1f-b6c5-46d9-ab2f-c70b229ab65b)

![Image](https://github.com/user-attachments/assets/aa76089a-b261-4e72-94ef-e5b79ef68fc0)

# Fix Gamification Modal z-index Issues

## Description
The gamification modals (completion, badges, feedback) in assessment lessons appear underneath other components instead of being the topmost layer. This causes UI/UX issues where users cannot properly see or interact with the modal content.

## Current State
In `src/app/features/lessons/assessment-lesson/assessment-lesson.component.scss`, modals like `.answer-feedback`, `.question-details-modal`, and `.completion-animation` have z-index values that don't ensure they appear above all other components.

## Bug Details
- Current z-index values:
  - `.answer-feedback`: z-index: 100
  - `.question-details-modal`: z-index: 200
  - `.completion-animation`: z-index: 300
- These values may not be high enough compared to other components in the application

## Steps to Reproduce
1. Complete a question in an assessment
2. Observe the feedback modal appearing behind other UI elements

## Proposed Fix
Update the z-index values in `assessment-lesson.component.scss`:

```scss
.answer-feedback {
  z-index: 1000; // Increase from 100
}

.question-details-modal {
  z-index: 1100; // Increase from 200
}

.completion-animation {
  z-index: 1200; // Increase from 300
}


Also, create a z-index hierarchy in src/styles/_variables.scss:
```scss
$z-index: (
  below: -1,
  base: 0,
  above: 1,
  header: 10,
  sidebar: 20,
  controls: 50,
  dropdown: 100,
  modal-base: 1000,    // Base for all modals
  modal-feedback: 1050, // Feedback modals
  modal-details: 1100,  // Detail views
  modal-completion: 1200, // Completion animations
  highest: 1500
);
```

### **Expected Outcome**
Gamification modals should always appear on top of other components, ensuring clear visibility and interaction.
