### ISSUE TITLE
Improve Questions Container Space Usage in Assessment Lessons

### ISSUE THREAD

**Issue by yassingamalz** [yassingamalz/Rateel#20]
# 📝 Improve Questions Container Space Usage in Assessment Lessons

## 🎯 Description
The assessment questions container doesn't utilize page space efficiently, especially on larger screens. We need to optimize the layout to show more content without requiring excessive scrolling.

## 🔍 Current State
In `src/app/features/lessons/assessment-lesson/assessment-lesson.component.scss`, the question container currently has:

## 🚀 Proposed Changes
```scss
.question-container {
 position: relative;
 flex: 1;
 overflow-y: auto;
 max-height: calc(100vh - 150px); // Reduce from 180px
 max-width: 90%;                  // Allow container to use more horizontal space
 margin: 0 auto;                  // Center the container
 
 // Responsive adjustments
 @media (min-width: 1200px) {
   max-width: 80%;                // Use more horizontal space on larger screens
 }
 
 // Improve readability with subtle background
 background: rgba(0, 0, 0, 0.05);
 border-radius: 12px;
 padding: 10px;
}

.question-card {
 margin-bottom: 15px;  // Reduced from 20px
 
 .question-meta {
   margin-bottom: 12px; // Reduced
 }
 
 .question-content {
   .question-text {
     margin-bottom: 15px; // Reduced from 20px
   }
 }
}

.options-container {
 margin-bottom: 15px; // Reduced from 20px
 
 .option-list {
   gap: 10px; // Reduced from 12px
   
   .option-item {
     padding: 12px; // Reduced from 15px
   }
 }
}
```
### **🌟 Expected Outcomes**
- More question content visible without scrolling
- Better overall space utilization, especially on larger screens
- Improved visual density without compromising readability
