### ISSUE TITLE
Improve Reading Component Number Display and UI/UX

### ISSUE THREAD

**Issue by yassingamalz** [yassingamalz/Rateel#6]
![Image](https://github.com/user-attachments/assets/d2acef82-b785-420b-abd9-d870a19d39e3)

# Improve Reading Component Number Display and UI/UX

## Problem Description
The current number display in the reading component lacks clarity and consistency.

## Current Issues
1. Number rendering appears inconsistent
2. Limited visual differentiation
3. Potential readability challenges

### 1. Number Display Refinement
- Implement consistent number styling
- Ensure clear visibility across different content
- Use Arabic-friendly number formatting

#### Typography
- Define clear hierarchy for numbers
- Ensure legibility
- Use appropriate font weight and size

#### Visual Treatment
- Add subtle background or border to number indicators
- Create visual separation
- Maintain app's design language

### 3. Accessibility Considerations
- Ensure high contrast
- Support screen readers
- Maintain responsive design

## Specific Implementation Suggestions

```scss
.reading-number {
  // Proposed styling
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 24px;
  height: 24px;
  border-radius: 50%;
  background: rgba(#DAA520, 0.2); // Use app's accent color
  color: #DAA520; // Accent color
  font-weight: 600;
  margin-left: 8px;
  transition: all 0.3s ease;

  &:hover {
    background: rgba(#DAA520, 0.3);
  }
}
```

## Acceptance Criteria
- [ ] Consistent number formatting
- [ ] Clear visual hierarchy
- [ ] Improved readability
- [ ] Responsive design
- [ ] Accessibility support

**Priority:** Low
**Type:** UI/UX Enhancement
