### ISSUE TITLE
Improve Lesson Card Layout Consistency

### ISSUE THREAD

**Issue by yassingamalz** [yassingamalz/Rateel#7]
![Image](https://github.com/user-attachments/assets/967978af-7310-4887-b114-ccb2f3c47a3f)

# Improve Lesson Card Layout Consistency

## Problem Description
Lesson cards with varying title lengths cause misalignment of duration indicators, leading to an inconsistent visual layout.

## Current Issues
- Duration time placement is not consistent across cards
- Long titles can disrupt the card's vertical alignment
- Inconsistent visual hierarchy

## Proposed Solution
Implement a flexible layout that:
- Maintains consistent card height
- Ensures duration is always aligned
- Handles variable title lengths gracefully

## Design Requirements
- Use flexbox or grid for precise alignment
- Implement max-height for title area
- Create a uniform card structure

## Example CSS Approach
```scss
.lesson-card {
  display: flex;
  flex-direction: column;
  
  &__content {
    flex-grow: 1;
    display: flex;
    flex-direction: column;
  }
  
  &__title {
    flex-shrink: 0;
    max-height: 3.6rem; // Limit to 2 lines
    overflow: hidden;
    text-overflow: ellipsis;
  }
  
  &__footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: auto; // Push to bottom
  }
}
```

## Acceptance Criteria
- [ ] Consistent card height
- [ ] Duration always aligned
- [ ] Long titles handled gracefully
- [ ] Responsive across different screen sizes

**Priority:** Medium
**Type:** UI Consistency Enhancement
